import { CuratedCandidate } from "@/types/quiz";

export const curatedCandidates: CuratedCandidate[] = [
  // --- U.S. Senate ---
  {
    id: "senate-rivera",
    name: "Maria Rivera",
    party: "Democratic",
    bio: "Former state attorney general with 12 years in public service. Known for prosecuting corporate fraud and advocating consumer protection.",
    isIncumbent: false,
    raceId: "us-senate",
    positions: [
      { category: "gun_policy", position: "Supports assault weapons ban, universal background checks", score: -0.8 },
      { category: "abortion", position: "Supports codifying Roe protections into federal law", score: -0.9 },
      { category: "immigration", position: "Supports path to citizenship, opposes family separation", score: -0.7 },
      { category: "taxes", position: "Raise taxes on incomes over $400K, expand child tax credit", score: -0.7 },
      { category: "education", position: "Increase federal education funding, universal pre-K", score: -0.7 },
      { category: "healthcare", position: "Expand ACA, add public option", score: -0.7 },
      { category: "housing", position: "Federal affordable housing investment, tenant protections", score: -0.7 },
      { category: "environment", position: "Supports Green New Deal framework, ban new fossil fuel leases", score: -0.8 },
      { category: "public_safety", position: "Police reform, ban chokeholds, community policing", score: -0.6 },
      { category: "transportation", position: "Invest in high-speed rail and public transit", score: -0.7 },
    ],
    endorsements: [
      { name: "Sierra Club", type: "organization" },
      { name: "Planned Parenthood Action Fund", type: "organization" },
      { name: "SF Chronicle", type: "newspaper" },
    ],
    votingHistory: [],
    website: "https://example.com/rivera",
  },
  {
    id: "senate-chen",
    name: "David Chen",
    party: "Republican",
    bio: "Tech entrepreneur and former city council member. Runs on fiscal responsibility and bipartisan problem-solving.",
    isIncumbent: false,
    raceId: "us-senate",
    positions: [
      { category: "gun_policy", position: "Protect 2nd Amendment, improve mental health screening", score: 0.5 },
      { category: "abortion", position: "Personally pro-life, supports exceptions. Opposes federal ban.", score: 0.3, priorPosition: "Supported 15-week ban in 2022", priorScore: 0.7 },
      { category: "immigration", position: "Secure border first, then reform legal immigration system", score: 0.6 },
      { category: "taxes", position: "Cut corporate tax rate, simplify tax code, no new income taxes", score: 0.8 },
      { category: "education", position: "Expand charter schools, school choice vouchers", score: 0.7 },
      { category: "healthcare", position: "Market-based reforms, reduce regulations, health savings accounts", score: 0.7 },
      { category: "housing", position: "Reduce zoning regulations, let the market build more", score: 0.3 },
      { category: "environment", position: "Support nuclear and natural gas, oppose mandates", score: 0.5 },
      { category: "public_safety", position: "Hire more police, tough on crime, enforce all laws", score: 0.8 },
      { category: "transportation", position: "Reduce gas tax, improve roads, private-public transit partnerships", score: 0.5 },
    ],
    endorsements: [
      { name: "Chamber of Commerce", type: "organization" },
      { name: "National Taxpayers Union", type: "organization" },
    ],
    votingHistory: [],
    website: "https://example.com/chen",
  },
  {
    id: "senate-ellis",
    name: "Jordan Ellis",
    party: "Independent",
    bio: "Nonprofit director focused on homelessness and housing policy. Centrist who rejects partisan gridlock.",
    isIncumbent: false,
    raceId: "us-senate",
    positions: [
      { category: "gun_policy", position: "Universal background checks, but protect lawful ownership", score: -0.2 },
      { category: "abortion", position: "Keep government out of reproductive decisions", score: -0.5 },
      { category: "immigration", position: "Secure borders AND humane treatment, expand legal pathways", score: -0.1 },
      { category: "taxes", position: "Targeted tax relief for middle class, close corporate loopholes", score: -0.2 },
      { category: "education", position: "Fund public schools but support innovation and charter pilots", score: 0.0 },
      { category: "healthcare", position: "Bipartisan fix for ACA, lower drug prices", score: -0.2 },
      { category: "housing", position: "Zoning reform and affordable housing mandates", score: -0.4 },
      { category: "environment", position: "Carbon tax, invest in clean energy and nuclear", score: -0.3 },
      { category: "public_safety", position: "Both community programs AND adequate policing", score: 0.0 },
      { category: "transportation", position: "Multi-modal investment: transit, roads, and biking", score: -0.2 },
    ],
    endorsements: [
      { name: "Independent Voter Project", type: "organization" },
    ],
    votingHistory: [],
    website: "https://example.com/ellis",
  },

  // --- U.S. Representative CA-11 ---
  {
    id: "house-washington",
    name: "Angela Washington",
    party: "Democratic",
    bio: "Three-term incumbent, former school board member. Champion of education funding and immigrant rights.",
    isIncumbent: true,
    raceId: "us-house-ca11",
    positions: [
      { category: "gun_policy", position: "Co-sponsored assault weapons ban", score: -0.9 },
      { category: "abortion", position: "Co-sponsored Women's Health Protection Act", score: -0.9 },
      { category: "immigration", position: "Supports DREAM Act, opposes ICE raids in schools", score: -0.8 },
      { category: "taxes", position: "Tax the ultra-wealthy, expand earned income tax credit", score: -0.8 },
      { category: "education", position: "Tripled Title I funding request, free school meals", score: -0.8 },
      { category: "healthcare", position: "Medicare expansion, lower prescription drug costs", score: -0.7 },
      { category: "housing", position: "Authored affordable housing bill, supports rent stabilization", score: -0.8 },
      { category: "environment", position: "100% clean energy by 2035, environmental justice focus", score: -0.9 },
      { category: "public_safety", position: "Police accountability, invest in alternatives to incarceration", score: -0.7 },
      { category: "transportation", position: "Federal transit funding increase, oppose highway expansion", score: -0.8 },
    ],
    endorsements: [
      { name: "American Federation of Teachers", type: "organization" },
      { name: "Congressional Progressive Caucus", type: "organization" },
      { name: "SF Examiner", type: "newspaper" },
      { name: "Sen. Maria Rivera", type: "official" },
    ],
    votingHistory: [
      { bill: "HR 1808 - Assault Weapons Ban", vote: "yes", date: "2024-03", summary: "Voted to ban semi-automatic assault weapons" },
      { bill: "HR 3684 - Infrastructure Investment", vote: "yes", date: "2023-11", summary: "Supported $1.2T infrastructure bill" },
      { bill: "HR 5376 - Build Back Better", vote: "yes", date: "2023-09", summary: "Supported social spending and climate package" },
    ],
    website: "https://example.com/washington",
  },
  {
    id: "house-nakamura",
    name: "Ken Nakamura",
    party: "Republican",
    bio: "Small business owner and veteran. Focused on economic growth, reducing regulations, and supporting working families.",
    isIncumbent: false,
    raceId: "us-house-ca11",
    positions: [
      { category: "gun_policy", position: "Protect Second Amendment, oppose new restrictions", score: 0.7 },
      { category: "abortion", position: "Pro-life with exceptions, opposes taxpayer funding", score: 0.6 },
      { category: "immigration", position: "Finish border wall, end catch-and-release, merit-based system", score: 0.8 },
      { category: "taxes", position: "Cut taxes for small businesses, oppose new tax increases", score: 0.8 },
      { category: "education", position: "School choice, parental rights in curriculum", score: 0.7 },
      { category: "healthcare", position: "Repeal ACA mandates, expand HSAs, tort reform", score: 0.7 },
      { category: "housing", position: "Cut red tape for builders, oppose rent control", score: 0.4 },
      { category: "environment", position: "All-of-the-above energy, support natural gas and nuclear", score: 0.5 },
      { category: "public_safety", position: "Back the blue, mandatory minimums for violent crime", score: 0.8 },
      { category: "transportation", position: "Fix roads first, reduce gas tax, oppose transit mandates", score: 0.6 },
    ],
    endorsements: [
      { name: "National Federation of Independent Business", type: "organization" },
      { name: "Veterans for America First", type: "organization" },
    ],
    votingHistory: [],
    website: "https://example.com/nakamura",
  },

  // --- State Senate District 11 ---
  {
    id: "state-senate-torres",
    name: "Sofia Torres",
    party: "Democratic",
    bio: "Former labor organizer and housing attorney. Champions tenant rights, transit equity, and environmental justice.",
    isIncumbent: false,
    raceId: "state-senate-11",
    positions: [
      { category: "gun_policy", position: "Support state assault weapons restrictions", score: -0.7 },
      { category: "abortion", position: "Expand reproductive healthcare access statewide", score: -0.8 },
      { category: "taxes", position: "Progressive income tax reform, tax wealth not work", score: -0.8 },
      { category: "education", position: "Fully fund public schools, oppose vouchers", score: -0.7 },
      { category: "housing", position: "Statewide rent control, social housing program", score: -0.9 },
      { category: "environment", position: "Ban fracking, 100% renewable by 2035", score: -0.9 },
      { category: "public_safety", position: "Invest in alternatives to policing, end cash bail", score: -0.8 },
      { category: "transportation", position: "Free public transit, expand rail, reduce car lanes", score: -0.8 },
      { category: "healthcare", position: "Single-payer healthcare for California", score: -0.9 },
      { category: "immigration", position: "Sanctuary state, state-funded legal aid for immigrants", score: -0.8 },
    ],
    endorsements: [
      { name: "California Labor Federation", type: "organization" },
      { name: "Sunrise Movement SF", type: "organization" },
    ],
    votingHistory: [],
  },
  {
    id: "state-senate-obrien",
    name: "Patrick O'Brien",
    party: "Democratic",
    bio: "Moderate Democrat and current supervisor. Pragmatist focused on business growth, balanced budgets, and public safety.",
    isIncumbent: false,
    raceId: "state-senate-11",
    positions: [
      { category: "gun_policy", position: "Support existing gun laws, focus on enforcement", score: -0.3 },
      { category: "abortion", position: "Pro-choice, maintain existing protections", score: -0.6 },
      { category: "taxes", position: "Hold the line on taxes, find efficiencies in government", score: 0.2 },
      { category: "education", position: "Fund public schools AND support charter innovation", score: 0.0 },
      { category: "housing", position: "Streamline permitting, incentivize building, oppose rent control expansion", score: -0.1 },
      { category: "environment", position: "Practical clean energy transition, support nuclear", score: -0.3 },
      { category: "public_safety", position: "Hire more police AND fund community programs", score: 0.2 },
      { category: "transportation", position: "Fix Muni, repair roads, balanced approach", score: -0.2 },
      { category: "healthcare", position: "Improve ACA, lower costs through market competition", score: -0.1 },
      { category: "immigration", position: "Support legal immigration, pragmatic border security", score: -0.1 },
    ],
    endorsements: [
      { name: "SF Moderate Alliance", type: "organization" },
      { name: "Small Business Coalition", type: "organization" },
      { name: "Mayor London Breed", type: "official" },
    ],
    votingHistory: [],
  },

  // --- Mayor of San Francisco ---
  {
    id: "mayor-kim",
    name: "Lisa Kim",
    party: "Nonpartisan",
    bio: "Former tech executive turned community leader. Promises data-driven solutions to SF's toughest problems.",
    isIncumbent: false,
    raceId: "sf-mayor",
    positions: [
      { category: "gun_policy", position: "Enforce existing restrictions, invest in violence prevention", score: -0.4 },
      { category: "taxes", position: "Reform business taxes, no new taxes without sunset clauses", score: 0.1 },
      { category: "education", position: "Modernize school facilities, STEM investment", score: -0.2 },
      { category: "housing", position: "Build 50,000 new units, streamline approval, mixed-income mandate", score: -0.4 },
      { category: "environment", position: "Carbon neutral by 2040, green building standards", score: -0.5 },
      { category: "public_safety", position: "Data-driven policing, community programs, and enforcement balance", score: 0.0 },
      { category: "transportation", position: "Fix Muni reliability, expand bike network, congestion pricing", score: -0.4 },
      { category: "healthcare", position: "Expand community clinics, address mental health crisis", score: -0.4 },
      { category: "immigration", position: "Maintain sanctuary city, expand immigrant services", score: -0.5 },
      { category: "abortion", position: "Protect reproductive rights at city level", score: -0.6 },
    ],
    endorsements: [
      { name: "Tech Workers for Good Government", type: "organization" },
      { name: "SF Chronicle", type: "newspaper" },
    ],
    votingHistory: [],
  },
  {
    id: "mayor-patel",
    name: "Raj Patel",
    party: "Nonpartisan",
    bio: "Community organizer from the Tenderloin. Grassroots progressive focused on housing justice and income equality.",
    isIncumbent: false,
    raceId: "sf-mayor",
    positions: [
      { category: "gun_policy", position: "Strict local gun regulations, buyback programs", score: -0.8 },
      { category: "taxes", position: "Tax large corporations, fund social programs", score: -0.8 },
      { category: "education", position: "Universal free meals, fully fund SFUSD", score: -0.7 },
      { category: "housing", position: "Social housing, 50% affordable mandate, ban corporate landlords", score: -0.9 },
      { category: "environment", position: "Aggressive climate action, ban gas in new construction", score: -0.8 },
      { category: "public_safety", position: "Defund police expansion, invest in community responders", score: -0.8 },
      { category: "transportation", position: "Free Muni, car-free Market Street, close streets to cars", score: -0.8 },
      { category: "healthcare", position: "Municipal single-payer pilot, safe injection sites", score: -0.8 },
      { category: "immigration", position: "Strongest sanctuary protections, municipal ID for all", score: -0.8 },
      { category: "abortion", position: "Expand reproductive care funding, protect clinic access", score: -0.8 },
    ],
    endorsements: [
      { name: "DSA SF Chapter", type: "organization" },
      { name: "Coalition on Homelessness", type: "organization" },
    ],
    votingHistory: [],
  },
  {
    id: "mayor-martinez",
    name: "Carlos Martinez",
    party: "Nonpartisan",
    bio: "Retired police captain and community leader. Centrist focused on public safety, clean streets, and accountable government.",
    isIncumbent: false,
    raceId: "sf-mayor",
    positions: [
      { category: "gun_policy", position: "Enforce existing gun laws, focus on illegal firearms", score: 0.1 },
      { category: "taxes", position: "No new taxes, audit city spending first", score: 0.4 },
      { category: "education", position: "Back to basics: reading, math, safety in schools", score: 0.2 },
      { category: "housing", position: "Build more market-rate housing, reduce regulations", score: 0.1 },
      { category: "environment", position: "Practical green policies that don't hurt small business", score: 0.0 },
      { category: "public_safety", position: "More police, enforce quality-of-life laws, clean up streets", score: 0.7 },
      { category: "transportation", position: "Fix potholes, keep parking, improve Muni efficiency", score: 0.3 },
      { category: "healthcare", position: "Mental health beds, treatment over tent camps", score: 0.1 },
      { category: "immigration", position: "Welcoming but lawful, cooperate on violent crime", score: 0.3 },
      { category: "abortion", position: "Personal matter, maintain current city protections", score: -0.2 },
    ],
    endorsements: [
      { name: "SF Police Officers Association", type: "organization" },
      { name: "TogetherSF", type: "organization" },
      { name: "Neighborhood Safety Coalition", type: "organization" },
    ],
    votingHistory: [],
  },

  // --- District Attorney ---
  {
    id: "da-zhao",
    name: "Michelle Zhao",
    party: "Nonpartisan",
    bio: "Public defender turned reform prosecutor. Believes in restorative justice and addressing root causes of crime.",
    isIncumbent: false,
    raceId: "sf-da",
    positions: [
      { category: "public_safety", position: "Diversion for nonviolent offenses, restorative justice programs", score: -0.7 },
      { category: "gun_policy", position: "Aggressively prosecute illegal gun possession", score: -0.3 },
      { category: "immigration", position: "Never use DA's office to assist deportation efforts", score: -0.7 },
      { category: "housing", position: "Prosecute wage theft, protect tenants from illegal eviction", score: -0.6 },
      { category: "healthcare", position: "Treatment courts for drug offenses, mental health diversion", score: -0.6 },
      { category: "environment", position: "Prosecute corporate environmental violations", score: -0.5 },
      { category: "taxes", position: "Pursue white-collar crime and tax fraud aggressively", score: -0.3 },
      { category: "education", position: "Youth diversion programs, keep kids out of juvenile hall", score: -0.6 },
      { category: "abortion", position: "Will not prosecute any reproductive healthcare", score: -0.7 },
      { category: "transportation", position: "Prosecute transit violence, support safety on Muni", score: -0.2 },
    ],
    endorsements: [
      { name: "ACLU Northern California", type: "organization" },
      { name: "Public Defender's Office Alumni", type: "organization" },
    ],
    votingHistory: [],
  },
  {
    id: "da-collins",
    name: "Robert Collins",
    party: "Nonpartisan",
    bio: "Veteran prosecutor with 20 years of trial experience. Promises to restore public safety and hold all offenders accountable.",
    isIncumbent: false,
    raceId: "sf-da",
    positions: [
      { category: "public_safety", position: "Prosecute all crimes consistently, mandatory minimums for violent repeat offenders", score: 0.7 },
      { category: "gun_policy", position: "Harsh penalties for gun crimes, enforce existing laws", score: 0.3 },
      { category: "immigration", position: "Cooperate with federal law enforcement on violent criminals", score: 0.4 },
      { category: "housing", position: "Prosecute property crime, protect homeowners", score: 0.3 },
      { category: "healthcare", position: "Mandate treatment for repeat drug offenders", score: 0.3 },
      { category: "environment", position: "Prosecute illegal dumping and environmental violations", score: 0.0 },
      { category: "taxes", position: "Tough on financial fraud", score: 0.1 },
      { category: "education", position: "Safe schools initiative, zero tolerance for campus crime", score: 0.4 },
      { category: "abortion", position: "Not a DA issue, focus on violent crime", score: 0.0 },
      { category: "transportation", position: "Prosecute fare evasion and transit safety threats", score: 0.4 },
    ],
    endorsements: [
      { name: "SF Police Officers Association", type: "organization" },
      { name: "Victims' Rights Coalition", type: "organization" },
      { name: "Neighborhood Safety Alliance", type: "organization" },
    ],
    votingHistory: [],
  },
];

export function getCandidateById(id: string): CuratedCandidate | undefined {
  return curatedCandidates.find((c) => c.id === id);
}

export function getCandidatesByRace(raceId: string): CuratedCandidate[] {
  return curatedCandidates.filter((c) => c.raceId === raceId);
}
